baseURL = "https://blog.tarasovic.cloud/"
title = "Opinions Were Like Kittens"

theme = "color-your-world"
languageCode = "en-us"
publishDir = "docs"

enableEmoji = true
enableInlineShortcodes = true
enableGitInfo = true


[markup]
[markup.highlight]
noClasses = false


[menu]
[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[params]
description = "Personal Blog of Jason Tarasovic"
author = "Jason Tarasovic"
authorDesc = "Some Dude"


[params.style]
isDark = true
ignoreSystemSettings = true
darkAccent = "#225670"


[params.social.centralized]
github        = [ "JTarasovic" ]
gitlab        = [ "J_Tarasovic" ]
keybase       = [ "jtarasovic" ]
linkedin      = [ "jtarasovic" ]
reddit        = [ "J_Tarasovic" ]
twitter       = [ "J_Tarasovic", "@j_tarasovic" ]

[params.social.decentralized]
